import '../styles/globals.css'
import Head from 'next/head'

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>News App 🍅</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header> 🍓 Newsapi </header>
      <Component {...pageProps} />
    </>
  );
}

export default MyApp
